spring:
  application:
    name: WhoIs-Server
  profiles:
    group:
      local : local-db, local-port, common
      prod: prod-db, prod-port,common
    active: local
---
# 로컬용 DB
spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
  data:
    redis:
      host: localhost
      port: 6379
---
# 개발용 DB
spring:
  config:
    activate:
      on-profile: prod-db
  datasource:
    url: ${PROD_DATASOURCE_URL}
    username: ${PROD_DATASOURCE_USERNAME}
    password: ${PROD_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
---
# 공통 속성
spring:
  config:
    activate:
      on-profile: common
  web:
    resources:
      add-mappings: false
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.timeout: 5000
#      mail.smtp.starttls.enable: true
#
jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_EXPIRED_IN}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRED_IN}

---
# 개발용 포트
spring:
  config:
    activate:
      on-profile: local-port
server:
  port: 8000
---
# 배포용 포트
spring:
  config:
    activate:
      on-profile: prod-port
server:
  port: 8001
